export const theme = {
    font1: 'Limelight',
    font2: 'KbLimelight',
    font3: 'Sassoon-Infant-Std',
    fontSize: '16px',
    wrapperXxs: '328px',
    wrapperXll: '546px',
    wrapperXs: '921px',
    wrapper: '1110px',
    wrapperLg: '1240px',
    wrapperLgx: '1254px',
    wrapperXl: '1368px',
    wrapperXxl: '1440px',
    wrapperXx: '1920px',
    wrapperXxx: '2670px',
    colors: {
        transparent: 'transparent',
        blue: '#1C2C7D',
        black: '#000000',
        white: '#FFFFFF',
        lightgray: '#CABEC5',
        gray: '#575757',
        gray2: '#C2C4BF',
        gray3: '#ADADAD',
        background: '#212529',
        rosy: '#FCC5BF',
        blueDark: '#152356',
        blueDark5: '#223581',
        blueGreen: '#225E81',
        lightpink: '#FCDEEF',
        backgroundPink: '#F7EDF4',
        backgroundColor: '#FFF8F0',
        yellow: '#E1D614',
        orange: '#F0700F',
    },

    gap: {
        xxs: '4px',
        xs: '8px',
        sm: '16px',
        smd: '24px',
        md: '32px',
        mdm: '40px',
        mdl: '36px',
        mdx: '52px',
        lg: '64px',
        xl: '72px',
        xxl: '128px',
    },

    divider: {
        top: 'inset 0px 1px 0px #d9dadd',
    },
} as const;
